export const wordList = [
  "but","little","a","I","first","words","called","people","going","still","mane","important","does","us","asked","different","me","through","big","mile","so","word","next","give","small","men","from","what","we","than","out","many","as","back","children","see","all","really","put","later","great","question","her","always","around","same","right","hear","here","eat","side","country","on","sometimes","you","had","soon","carry","add","high","know","city","far","at","each","car","read","time","there","kind","made","came","no","something","plant","school","air","change","water","paper","river","idea","found","open","number","how","eye","has","long","tree","talk","want","mountain","about","near","or","again","list","almost","while","would","life","make","set","girl","well","last","large","enough","them","only","show","some","most","once","can","take","could","like","two","in","head","their","state","mean","begin","it","to","think","way","will","young","my","family","should","name","which","say","these","up","after","those","together","world","took","under","not","learn","said","good","thing","who","white","day","left","where","part","because","before","never","try","get","are","tell","ask","house","place","run","with","him","just","saw","thought","might","and","between","man","any","our","his","go","over","an","turn","much","cut","into","another","your","point","by","write","help","every","its","example","start","too","sound","boy","call","now","be","letter","both","face","live","animal","other","end","if","follow","then","do","above","this","three","the","miss","oil","seem","line","away","was","let","that","why","find","have","come","below","old","they","did","new","answer","hand","without","is","book","form","work","until","when","quickly","feet","move","went","sentence","food","year","she","stop","may","sea","play","quick","spell","group","of","also","home","along","been","song","second","being","very","one","story","even","off","such","page","hard","down","use","light","own","look","land","few","often","got","don't","father","more","leave","must","mother","it's","were","walk","watch","picture","quite","close","for","he","study","keep","four"
];

export function shuffle(a) {
   for (let i = a.length - 1; i > 0; i--) {
       const j = Math.floor(Math.random() * (i + 1));
       [a[i], a[j]] = [a[j], a[i]];
   }
   return a;
}
